#!/bin/bash

set -x

set -eo pipefail

XDG_CONFIG_HOME=/tmp/.config
export XDG_CONFIG_HOME
export THEIA_DEFAULT_PLUGINS=local-dir:/opt/theia/plugins

cd /opt/theia

exec yarn theia start --hostname 127.0.0.1 --port 10085 /home/eduk8s